### ISSUE TITLE
Make a deb package

### ISSUE THREAD

**Issue by HumanG33k** [DocMarty84/koozic#10]
Make a deb package for improve the adoption of the software.

**Comment by DocMarty84** [comment]
Unfortunately, there is no plan for this. Packaging is a time-consuming task, and at the moment I don't have time to maintain packages on various distributions. This might change in the future, but clearly not for the upcoming year.

However, the installation script should make the process straightforward: https://koozic.net/installation/#TLDR If you face any problem at installation, do not hesitate to open an issue.

I will close this issue, since there won't be any update on this topic soon. Thanks for the report anyway.
