### ISSUE TITLE
Albums greater than 10 tracks sorted incorrectly

### ISSUE THREAD

**Issue by lxea** [DocMarty84/koozic#18]
Hey, I've discovered that if an album has more than 10 tracks in it it is sorted incorrectly ie:
![image](https://user-images.githubusercontent.com/7910815/51091289-d64af480-1780-11e9-87c7-7e8a7d08fd28.png)

**Comment by DocMarty84** [comment]
Indeed, that's because of the "/20". Track numbers like:
- 01, 02, 03..
- 1, 2, 3...
- 01/10, 02/10, 03/10...

will work. But you have "1/10, 2/10, 3/10..." and that doesn't work. That's an easy fix though, I will check today.

For reference: https://github.com/DocMarty84/oomusic/blob/0f4ea4a029b2915c918914ed656a384edcc495b6/models/oomusic_folder_scan.py#L535

**Comment by DocMarty84** [comment]
Fixed with https://github.com/DocMarty84/oomusic/commit/2190011f440be9688158c15c244d2f2f39236100

Thanks for reporting!
