### ISSUE TITLE
On the fly transcoding

### ISSUE THREAD

**Issue by alfureu** [DocMarty84/koozic#26]
Do I understand it correctly that I can send batches of files for transcoding to a folder, but Koozic is not able to transcode for DSub files on the fly? Would it be possible to implement it?

**Comment by DocMarty84** [comment]
Hello,

You can indeed send a batch of files for transcoding to a folder, but that's just a feature added for convenience.

Transcoding is done on the fly when playing tracks in the web interface or in DSub. Long story short: you shouldn't have to worry about transcoding at all, it is done on the fly when necessary.

**Comment by alfureu** [comment]
Hi @DocMarty84, thanks for the reply. Actually, I am concerned about the transcoding, as I would like to use Koozic with DSub on a mobile device (and mobile network). What I see at the moment is that my flac files are transcoded on the fly to mp3 files, but each file is approx ~17MB, which I suspect are 320kbps mp3 quality. 

I would like to be able to define for myself what the flac files are transcoded into, and not only in the bulk conversion, but also for on the fly conversion. I am interested in Opus 96kbps conversion for DSub, which can play this format. 

Is there a way where to set it? If not, can it be implemented? I have ffmpeg installed, and it should be a matter of 1 line of setting for me.

**Comment by DocMarty84** [comment]
> What I see at the moment is that my flac files are transcoded on the fly to mp3 files, but each file is approx ~17MB, which I suspect are 320kbps mp3 quality.

Indeed, this is the default value. However, you can set the quality directly in DSub, you can even specify a different quality if you fetch the track on wifi or mobile data. KooZic will transcode according to the quality set in DSub.

> I would like to be able to define for myself what the flac files are transcoded into

For compatibility reason, transcoding through the Subsonic API is only done in MP3 since it is the only format the official Subsonic server uses. However, that's pretty straightforward if you wish to change it:

https://github.com/DocMarty84/oomusic/blob/c183b528e3d2a35f746b8ec5aab32988c12053a4/controllers/subsonic/media_retrieval.py#L38

Just replace with:

``` python
output_format = kwargs.get('format', 'opus')
```

and restart the server.

(note: I didn't test it personally, if it fails I'll check in more details.)

**Comment by alfureu** [comment]
Hm, ok, but I cannot find this file in the docker I just installed from you. Can you help where is it?

**Comment by DocMarty84** [comment]
Hum with Docker... The Docker image is not built with such modifications possible. But it can be made, although it is hackish and I **do not recommend it**. I'd advise you to keep the MP3 format. 160-192kbps MP3 is usually good enough for smartphones. Moreover, DSub has a maximum cache size, so it can automatically clear up cached tracks once they take up too much space.

Anyway... the trick is to modify the `Dockerfile` in order to patch the file during the installation process.

1. Clear-up the existing image: run `docker-compose down` in the folder where you extracted the `.tar.gz` archive
2. In the `Dockerfile`, change:

```
RUN set -x; \
        tar xfz koozic/extra/ffmpeg/ffmpeg-*-64bit.tar.gz -C /usr/local/bin && \
        mv koozic /usr/local/ && \
        chown -R koozic /usr/local/koozic
```

into:


```
RUN set -x; \
        tar xfz koozic/extra/ffmpeg/ffmpeg-*-64bit.tar.gz -C /usr/local/bin && \
        mv koozic /usr/local/ && \
        sed -i 's/mp3/opus/g' /usr/local/koozic/addons/oomusic/controllers/subsonic/media_retrieval.py && \
        chown -R koozic /usr/local/koozic
```

3. Run:

```
docker-compose build
docker-compose up -d
```

DSub is able to read such files, but if you check in the DSub cache you'll still find the files named `***.mp3`. However, they are genuine Opus files:

```
~ $ file test.mp3 
test.mp3: Ogg data, Opus audio,
```

So that's a bit weird: you get `.mp3` files which are actually Opus files...

**Comment by alfureu** [comment]
Very interesting. Thanks for sharing the hack. 

On this note, I was wondering, whether it won't be easier to allow the user to change/choose the encoder/transcoder to his/her needs as a drop-down menu.

My use case unfortunately cannot accept MP3 on 160-192kbps, as I would use 95% of the time my music server for mobile playback through mobile data (maxxed to 4GB/mo). I was easily hitting my limit with MP3 in a week, while Opus with 96kbps (~same quality as the aforementioned MP3 encoding) I am comfortably within my data limits through the month. Hence the request, and I am sure I am not alone.

For comparison, I am getting 17MB file for MP3, while Opus is 2MB. Quite a significant difference!

**Comment by DocMarty84** [comment]
> On this note, I was wondering, whether it won't be easier to allow the user to change/choose the encoder/transcoder to his/her needs as a drop-down menu.

Sure. I had the request once, since you are also asking for it I can add it. Just get the [v2.2.0-beta.2](https://github.com/DocMarty84/koozic/releases/tag/v2.2.0-beta.2) version and follow the regular instructions.

You'll get a new option in the settings:

![Screenshot_2019-06-27 Odoo](https://user-images.githubusercontent.com/386952/60298590-1f57c500-992b-11e9-8695-2b1b18e7d5cd.png)

**Comment by alfureu** [comment]
Hi @DocMarty84, I just installed it and tested, I can confirm this works flawlessly. Just for fine-tuning this, would it be possible to change the extension of the file from mp3 to opus, when one selects the Opus option? I am asking as DSub plays the file nicely, VLC expects somehow mp3 and does not play. 

In any case, BIG BIG THANKS! Well done.

**Comment by DocMarty84** [comment]
Release [v2.2.0-beta.3](https://github.com/DocMarty84/koozic/releases/tag/v2.2.0-beta.3) should solve the issue.

**Comment by DocMarty84** [comment]
Please note that in the final release, this option will displayed only debug mode since it is an advanced configuration. To display it, you'll have to add `?debug` in the url: `http://<my_host>/web?debug`

**Comment by alfureu** [comment]
Any reason? I think it is good to be able to fine-tune the format of choice 🙄

**Comment by DocMarty84** [comment]
Yes: there are only few cases where you'd like to fine-tune such a configuration. Most of the time, MP3 is just fine and works out-of-the box on all devices, with all apps. I want to avoid people to blindly change settings then complain that things don't work.

Note that the option will still accessible in debug mode, it's just that it is hidden in the regular mode.
