### ISSUE TITLE
indexing

### ISSUE THREAD

**Issue by aroundmyroom** [DocMarty84/koozic#4]
I am about to install Koozic on a VM (locally hosted at home) where I will mount my Music database (NFS) towards an debian 9 machine with Koozic on it.

On of the reason is that subsonic seems to stall its development after 6.1.3 even the author is visiting its own forum only once every 6 weeks or so .. 

So I am looking for an alternative and nothing is serving my needs fully yet .. 

- Some questions: is Koozic storing all its data in de db? So it does not need write access towards the NFS share adding hidden files into folders?
- How is indexing arranged?
- I have around 4TB of music in 145.500 songs, 8161 artists and 21K of albums (according to subsonic) so I wonder how Koozic is handling this amount of data 

yes, I will know this later this week, but would love to know ;l)

**Comment by DocMarty84** [comment]
Thanks for your interest!

> is Koozic storing all its data in de db? So it does not need write access towards the NFS share adding hidden files into folders?

It uses PostgreSQL to store all data and the folder `~/.local/share/Odoo/filestore` to store the image cache (plus some extra files necessary). KooZic doesn't write anything on your music folder, so it does not need write access.

Just keep in mind that you might need to deactivate the auto-scan feature (it is just a checkbox on the folder setup) if your NFS share is not always mounted. Otherwise, KooZic will automatically remove from the database any track not found. Therefore, if your folder is not mounted during a scan, it will remove all tracks from the DB.

I personally use AutoFS + SSHFS, and that works great.

> How is indexing arranged?

I'm not sure I get the question, but KooZic extensively uses ID3 tags. That was one of its main purpose. If your music is not correctly tagged, you can still use the browsing mode, but that's clearly limited and provided for convenience purpose.

> I have around 4TB of music in 145.500 songs, 8161 artists and 21K of albums (according to subsonic) so I wonder how Koozic is handling this amount of data

It should be fine, there should not be any bottleneck regarding the number of tracks. The initial scan is able to scan ~2000 tracks / minute, but of course that depends on your system (especially with network shares).

I will detail later this day some points for upcoming developments.

**Comment by aroundmyroom** [comment]
Great .. let me start setting up the VM ;) to test this new software

update.. setting up vm with debian9, than the installation: easy, and quick first music already playing (I like that) even the indexing is not yet read (far from that) ;)
