### ISSUE TITLE
Missing: search function

### ISSUE THREAD

**Issue by aroundmyroom** [DocMarty84/koozic#6]
Missing a good search function 

after around 5 hours the whole 4TB of music is indexed. Good job ! (unfortunately no figures about that from the database) 

till so far it is playing my music . Will need longer tests.

**Comment by DocMarty84** [comment]
> Missing a good search function

Have you explored all the possibilities: https://drive.google.com/open?id=1h0nm3aRKFTH3FtScd_dRz7c7vOB0L8jb

KooZic has quite a lot of search capabilities, given that the ID3 tags are set up correctly. You can always search for "Path" under the "Tracks" menu to search on the complete path of the file. Adding to a playlist is afterwards straightforward.

> after around 5 hours the whole 4TB of music is indexed. 

So it's around 500 tracks/minute. Still decent, but of course network performance might play a major role in your case since it is on a NFS share.

> Good job ! (unfortunately no figures about that from the database)

Indeed, the only figure you get is the total tracks / albums / artists found (see https://screenshots.firefox.com/UlKb52YcoHuLj7d1/demo.koozic.net). It is updated every 1000 tracks indexed. Other than that, what kind of figures would you expect?

**Comment by aroundmyroom** [comment]
the tracks option does the job for the search, did miss that one this afternoon.

This I would like to see like subsonic
![image](https://user-images.githubusercontent.com/250108/38946907-31e5265a-433b-11e8-92ae-1282fdfcfc84.png)

and about the performance of NFS
![image](https://user-images.githubusercontent.com/250108/38946981-657b8946-433b-11e8-93a5-12d85aae7865.png)  
the VM is running on 1CPU with 1024MB Memory and 16GB disk with Debian 9 
soley for Koozic). 

Also tested the good old iSUB iphone subsonic player and that one is working fine with koozic as well

**Comment by aroundmyroom** [comment]
update .. actually the index was much faster .. 

![image](https://user-images.githubusercontent.com/250108/38947311-8e49cbfc-433c-11e8-87c7-9a33b16d20fe.png)
12:30 start -and ready around 16.15 .. so 3.45 ..

**Comment by DocMarty84** [comment]
> This I would like to see like subsonic

Added in https://github.com/DocMarty84/oomusic/commit/8c5b64fc83e4c18b9ded70525036553096a5b562 Will be released with v1.0.0 (hopefully end of May).

> Also tested the good old iSUB iphone subsonic player and that one is working fine with koozic as well

Good to know! That's kind of a nightmare to test all these apps. Moreover, issues might arise because of incorrect tags (e.g. the year is set to 2018-01-01 instead of 2018), so it's always good to have somebody with a lot of files testing the apps.
I am not using an iPhone, but last time I checked [play:Sub](https://itunes.apple.com/us/app/play-sub-subsonic-music-streamer/id955329386?mt=8) was the best one (but it's not free). 
For Android, [DSub](https://github.com/daneren2005/Subsonic/releases) is great. I know that Ultrasonic is not working well with v0.8.0 (I realized that a few days ago), but most of the issues should be fixed with https://github.com/DocMarty84/oomusic/commit/d18e22c1ecf655869f638cf886ba2b23143f8c0f

**Comment by aroundmyroom** [comment]
My music files are with and without tags and I need for that the filename and folder ;) Due to that it was a long search to an alternative. Right now all subsonic clones do fail due to all kind of issues. Madsonic is ok but is not free ;) KOEL I tried long time ago and was install nightmare and other alternatives as well never there was one where I could browse a folder pick the music. A nice feature of subsonic is the 'random'  part refreshing itself (a little too fast) where I can pick simple song by song when I am at work , but now I will gives this a try.  Thanks for fixing this, I will not switch brances ;) and wait for the update.  Will check today how the peformance is when not indexing

**Comment by DocMarty84** [comment]
> Due to that it was a long search to an alternative.

You can change the search order if you want: https://drive.google.com/open?id=1T4oFhbGoewZ0mlac3WZuPPYNHudfKncs
Might be more convenient to search on path.

> was install nightmare and other alternatives as well

Yeah, "2-clicks" installation is often "2-clicks after tens of small things to set-up here and there beforehand (e.g. set-up Apache)". I've been there. Did you use the install script as explained [here](https://koozic.net/installation/#TLDR)?

> A nice feature of subsonic is the 'random' part refreshing itself

There are random songs available in the "Suggestion", but that doesn't refresh automatically (and this probably will never be the case). Just note that every time you click on "Suggestion", the list is refreshed with new songs.

> Thanks for fixing this, I will not switch brances

You should not ;-) This is the development version, and moreover the v1.0.0 (Python 3) won't be directly compatible with v0.8.0 (Python 2). I'll give the necessary information on how to switch from one to another when it is released.
